/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;

/**
 *
 * @author pablo
 */
public class ControlLibros extends javax.swing.JFrame {

    /**
     * Creates new form ControlLibros
     */
    public ControlLibros() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_registrar_libros = new javax.swing.JButton();
        btn_consulta_sanciones = new javax.swing.JButton();
        btn_consulta_libros = new javax.swing.JButton();
        btn_registrar_autor = new javax.swing.JButton();
        btn_consultar_prestamos = new javax.swing.JButton();
        btn_registrar_librosbiblio = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btn_registroPrestamo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Menú Libros");

        btn_registrar_libros.setText("Registrar Libro");
        btn_registrar_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_librosActionPerformed(evt);
            }
        });

        btn_consulta_sanciones.setText("Consultar Sanciones");
        btn_consulta_sanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consulta_sancionesActionPerformed(evt);
            }
        });

        btn_consulta_libros.setText("Consultar Libros");
        btn_consulta_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consulta_librosActionPerformed(evt);
            }
        });

        btn_registrar_autor.setText("Registrar Autor");
        btn_registrar_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_autorActionPerformed(evt);
            }
        });

        btn_consultar_prestamos.setText("Consultar Préstamos");
        btn_consultar_prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_prestamosActionPerformed(evt);
            }
        });

        btn_registrar_librosbiblio.setText("Registrar Libro Biblioteca");
        btn_registrar_librosbiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_librosbiblioActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver atrás");

        btn_registroPrestamo.setText("Registrar Préstamos");
        btn_registroPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_consulta_sanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_consulta_libros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_registrar_libros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_registrar_librosbiblio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_registrar_autor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_consultar_prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_registroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_registrar_libros)
                .addGap(18, 18, 18)
                .addComponent(btn_registrar_librosbiblio)
                .addGap(12, 12, 12)
                .addComponent(btn_consulta_libros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consulta_sanciones)
                .addGap(12, 12, 12)
                .addComponent(btn_registrar_autor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultar_prestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_registroPrestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrar_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_librosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrar_librosActionPerformed

    private void btn_consulta_sancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consulta_sancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consulta_sancionesActionPerformed

    private void btn_consulta_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consulta_librosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consulta_librosActionPerformed

    private void btn_registrar_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrar_autorActionPerformed

    private void btn_consultar_prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_prestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar_prestamosActionPerformed

    private void btn_registrar_librosbiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_librosbiblioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrar_librosbiblioActionPerformed

    private void btn_registroPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registroPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlLibros().setVisible(true);
            }
        });
    }

    public JButton getBtn_consulta_libros() {
        return btn_consulta_libros;
    }

    public JButton getBtn_consulta_sanciones() {
        return btn_consulta_sanciones;
    }

    public JButton getBtn_registrar_librosbiblio() {
        return btn_registrar_librosbiblio;
    }

    public void setBtn_registrar_librosbiblio(JButton btn_registrar_librosbiblio) {
        this.btn_registrar_librosbiblio = btn_registrar_librosbiblio;
    }

    public JButton getBtn_consultar_prestamos() {
        return btn_consultar_prestamos;
    }

    public JButton getBtn_registrar_autor() {
        return btn_registrar_autor;
    }

    public JButton getBtn_registrar_libros() {
        return btn_registrar_libros;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }

    public JButton getBtn_registroPrestamo() {
        return btn_registroPrestamo;
    }

    public void setBtn_registroPrestamo(JButton btn_registroPrestamo) {
        this.btn_registroPrestamo = btn_registroPrestamo;
    }

    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btn_consulta_libros;
    private javax.swing.JButton btn_consulta_sanciones;
    private javax.swing.JButton btn_consultar_prestamos;
    private javax.swing.JButton btn_registrar_autor;
    private javax.swing.JButton btn_registrar_libros;
    private javax.swing.JButton btn_registrar_librosbiblio;
    private javax.swing.JButton btn_registroPrestamo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
